name: Theme deploy

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli

      - name: Upload theme
        run: |
          if [ "${{ github.head_ref || github.ref_name }}" == "production" ]; then
            shopify theme push \
              --json \
              --ignore config/settings_data.json templates/*.json sections/*.json \
              --theme ${{ vars.PRODUCTION_THEME_NAME }} \
              --store ${{ secrets.SHOPIFY_STORE }} \
              --password ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }} \
              --allow-live
          elif [ "${{ github.head_ref || github.ref_name }}" == "development" ]; then
            shopify theme push \
              --json \
              --ignore config/settings_data.json templates/*.json sections/*.json \
              --theme ${{ vars.DEVELOPMENT_THEME_NAME }} \
              --store ${{ secrets.SHOPIFY_STORE }} \
              --password ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          fi